language: python
python:
- 3.6
install:
- pip install -U tox-travis coverage codecov
- pip install -r requirements.txt
script:
- tox
- coverage run --source pbcluster -m pytest
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: benlindsay
  password:
    secure: FT66tJs0ey3XpiVN/jq4TA8aQ/jyoahpqqo+gpbhFXZmM+2iG1vM1FiiETgMw+b7HUyFZuvP/NIW6yAlTLbebwBKfifjbATENfoiIM0j8JsA/UHMGsrd7ILI2fGELQKftNVzPTL+DHraJo0f2i0GHh9g+wB7E1Rf11/iAtTr/is29QryR/KUU3fKt6KnIpvVoCI0D0/PKdM5H1kjp4s9ntq5n2cI34nqzhuZDskVMj8D8x+JknO7vEPZd3jPq5MfoLwLCaPy728n9emNj+0yZWa3kaD/6SJJXKI+2BumvF8rEmPtxp8/rTQpxNdP8GmuQbYfYJ0j+EIUmv6dnzXQMh/+SxfAAcreCl2IO+N+axD4IPbrg1+NEof+KpSdUaYiZjFdhTCwEtpjGCYoSNhO9GNg7fVAIYQd12HjyDsyk70Eh7PY3ffXiWmwd3ld+Hjh2g+/c8aMA+gJvz3pFTo3SsilVx6DUbL8YHKJDMlKbZWCdFLIjj10+Ab4C+CZh3LIKdIJtnzOUeMlQSld3kzFDFoeSWiCV+9rNCfDBmHVFeyzpbuHCWGMWqvKhHA1Oo3EmcfPWz2gNr4iWNZ5WVzII2848fLqnQ7rWjQKSKvhby+dTXQ2KBQW8DF0Z9k7cyWPFcSmvEnjVE7RfbfBgJsNALCB9DC6FQzA5gH7yNHaxnU=
  on:
    tags: true
    repo: benlindsay/pbcluster
    python: 3.6
