name: pbcluster
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  # package dependencies
  - networkx>=2.1
  - numpy
  - pandas
  - plotnine
  - scikit-learn
  - scipy
  - pygraphviz
  # dev dependencies
  - black
  - bumpversion
  - coverage
  - flake8
  - jupyter
  - mock
  - nbsphinx
  - pre_commit
  - pylint
  - pytest
  - pytest-runner
  - Sphinx
  - sphinx_rtd_theme
  - tox
  - twine
  - watchdog
  - pip:
    - sphinxcontrib-napoleon
