name: pbcluster
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  # package dependencies
  - networkx
  - numpy
  - pandas
  - plotnine
  - scikit-learn
  - scipy
  - pygraphviz
  # dev dependencies
  - black
  - bumpversion
  - coverage
  - flake8
  - pre_commit
  - pylint
  - pytest
  - pytest-runner
  - Sphinx
  - watchdog
  - tox
  - twine
